let ol1 = document.createElement('ol');
console.log(ol1);
let li1 = document.createElement('li');
let li2 = document.createElement('li');
let li3 = document.createElement('li');
let li4 = document.createElement('li');
let li5 = document.createElement('li');
let li11 = document.createElement('p');
li1.textContent = 'java script';
li2.textContent = 'css ';
li3.textContent = 'html';
li4.textContent = 'jangular js';
li5.textContent = 'react js';
li11.textContent = '*******orderd list***********';
let list = document.getElementById('hi');
list.appendChild(ol1);
ol1.appendChild(li1);
ol1.appendChild(li2);
ol1.appendChild(li3);
ol1.appendChild(li4);
ol1.appendChild(li5);
list.appendChild(li11)
let ul1 = document.createElement('ul');
let li6 = document.createElement('li');
let li7 = document.createElement('li');
let li8 = document.createElement('li');
let li9 = document.createElement('li');
let li10 = document.createElement('li');
let li12 = document.createElement('p');
li6.textContent = 'java script';
li7.textContent = 'css ';
li8.textContent = 'html';
li9.textContent = 'jangular js';
li10.textContent = 'react js';
li12.textContent = '*******unordered list*********';
let list1 = document.getElementById('hi');
list.appendChild(ul1);
ul1.appendChild(li6);
ul1.appendChild(li7);
ul1.appendChild(li8);
ul1.appendChild(li9);
ul1.appendChild(li10);
list1.appendChild(li12)