let tabel1 = document.createElement('tabel');
let thead = document.createElement('thead');
let tr1 = document.createElement('tr');
console.log(tr1)
let td1 = document.createElement('td');
td1.textContent= 'Name';
let td2 = document.createElement('td');
td2.textContent= 'age';
let td3 = document.createElement('td');
td3.textContent = 'address';
let td4 = document.createElement('td');
td4.textContent='D-O-B';
document.body.appendChild(tabel1);
tabel1.appendChild(thead);
thead.appendChild(tr1);
tr1.appendChild(td1);
tr1.appendChild(td2);
tr1.appendChild(td3);
tr1.appendChild(td4);
let tr2 = document.createElement('tr');
console.log(tr2)
let td5 = document.createElement('td');
td5.textContent= 'bhanu prakash reddy y';
let td6 = document.createElement('td');
td6.textContent= '21';
let td7 = document.createElement('td');
td7.textContent = '#itikanelore(v&p),chittor(d)';
let td8 = document.createElement('td');
td8.textContent='5-8-18';
thead.appendChild(tr2);
tr2.appendChild(td5);
tr2.appendChild(td6);
tr2.appendChild(td7);
tr2.appendChild(td8);
let tr3 = document.createElement('tr');
console.log(tr2)
let td11 = document.createElement('td');
td11.textContent= 'ram bupal reddy y';
let td12 = document.createElement('td');
td12.textContent= '23';
let td13 = document.createElement('td');
td13.textContent = '#itikanelore(v&p),chittor(d)';
let td14 = document.createElement('td');
td14.textContent='29-5-18';
thead.appendChild(tr3);
tr3.appendChild(td11);
tr3.appendChild(td12);
tr3.appendChild(td13);
tr3.appendChild(td14);
