console.log("====================");
var hobbies = ['singing','dancing','cricket','football','monoacting'];
var checkArray = Array.isArray(hobbies);
console.log('Is Array = '+checkArray);
var checkIncludes = hobbies.includes('dancing');
console.log('Includes = '+checkIncludes);
hobbies.push('kabbadi','volleyball');
console.log('Hobbies After Push '+hobbies);
hobbies.pop();
console.log('Hobbies After Pop '+hobbies);
console.log("====================");
var hobbies = ['singing','dancing','cricket','football','monoacting'];
var checkArray = Array.isArray(hobbies);
console.log('Is Array = '+checkArray);
var checkIncludes = hobbies.includes('dancing');
console.log('Includes = '+checkIncludes);
hobbies.push('kabbadi','volleyball');
console.log('Hobbies After Push '+hobbies);
hobbies.pop();
console.log('Hobbies After Pop '+hobbies);
hobbies.unshift('skipping','shopping');
console.log('Hobbies after unshift '+hobbies);
hobbies.shift();
console.log('Hobbies After Shift '+hobbies);